# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Memories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todays_memory',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
